name: 毎日の自動投稿

on:
  # schedule:
  #   # 毎日 UTC 23:00 (JST 8:00) に実行
  #   - cron: "0 23 * * *"
  workflow_dispatch: # 手動実行用トリガー

jobs:
  post-to-note:
    runs-on: ubuntu-22.04

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3

      - name: Node.js のセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Chromiumの依存パッケージをインストール
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget

      - name: 依存パッケージのインストール
        run: npm ci

      - name: TypeScriptのビルド
        run: npm run build

      - name: 自動投稿スクリプトの実行
        run: node dist/index.js
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          NOTE_USER: ${{ secrets.NOTE_USER }}
          NOTE_PASSWORD: ${{ secrets.NOTE_PASSWORD }}
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome-stable

      # - name: 実行結果の通知
      #   if: always()
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      #     SLACK_CHANNEL: note-auto-post
      #     SLACK_TITLE: Note自動投稿結果
      #     SLACK_MESSAGE: ${{ job.status == 'success' && '✅ 投稿成功しました' || '❌ 投稿に失敗しました' }}
      #     SLACK_COLOR: ${{ job.status == 'success' && 'good' || 'danger' }}
